### ISSUE TITLE
Could you please note how to run example or using this system from start

### ISSUE THREAD

**Issue by takaaptech** [UniGameTeam/UniGame.ViewSystem#15]
I just import this package done but can not let the ~Example run correctly. 

I am following the tut: Add to your project manifiest by path
[%UnityProject%]/Packages/manifiest.json these lines ...
And after import View System, I move the ~Example to the Assets folder and run (Because we can not run the scene in the package folder)
The scene then runs without error but when pressing a button, nothing shows or hides.

Could you please add some notes on how to test this awesome package?
Or maybe some simple step to create new screen and window to test.
Thank you so much!

**Comment by Mefodei** [comment]
Hello there. I will move all demo project into separate Unity project with all correct settings. After that your can try it. About Examples publish day, i think that's 11.04.2021.

If your have any other questions we are ready to help :)

**Comment by takaaptech** [comment]
@Mefodei Thank you so much! I will ask for your help when learning more about the UniGame Modules!
